# Generated by Django 4.2.25 on 2025-10-16 10:16

from django.db import migrations, models
from django.db.models import Case, When, Value, IntegerField


def anime_season_choice_text_to_int(apps, schema_editor):
    Anime = apps.get_model('api', 'Anime')
    Anime.objects.update(
        season_int=Case(
            When(season='spring', then=Value(0)),
            When(season='summer', then=Value(1)),
            When(season='fall', then=Value(2)),
            When(season='winter', then=Value(3)),
            default=None,
            output_field=IntegerField()
        )
    )


def character_role_choice_text_to_int(apps, schema_editor):
    Character = apps.get_model('api', 'Character')
    Character.objects.update(
        role_int=Case(
            When(role='main', then=Value(0)),
            When(role='supporting', then=Value(1)),
            default=Value(0),
            output_field=IntegerField()
        )
    )


def image_role_choice_text_to_int(apps, schema_editor):
    Image = apps.get_model('api', 'Image')
    Image.objects.update(
        type_int=Case(
            When(type='jpg', then=Value(0)),
            When(type='webp', then=Value(1)),
            default=Value(0),
            output_field=IntegerField()
        )
    )


def watchlist_type_choice_text_to_int(apps, schema_editor):
    Watchlist = apps.get_model('api', 'Watchlist')
    Watchlist.objects.update(
        type_int=Case(
            When(type='watch_later', then=Value(0)),
            When(type='watching', then=Value(1)),
            When(type='watched', then=Value(2)),
            default=Value(0),
            output_field=IntegerField()
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        # Add Temporary Fields
        migrations.AddField(
            model_name='anime',
            name='season_int',
            field=models.IntegerField(blank=True, choices=[(0, 'Spring'), (1, 'Summer'), (2, 'Fall'), (3, 'Winter')],
                                      null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='role_int',
            field=models.IntegerField(choices=[(0, 'Main'), (1, 'Supporting')], default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='type_int',
            field=models.IntegerField(choices=[(0, 'jpg'), (1, 'webp')], default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='type_int',
            field=models.IntegerField(choices=[(0, 'watch_later'), (1, 'watching'), (2, 'watched')], default=0),
        ),

        # Migrate data from text based choices to integer based choices
        migrations.RunPython(anime_season_choice_text_to_int),
        migrations.RunPython(character_role_choice_text_to_int),
        migrations.RunPython(image_role_choice_text_to_int),
        migrations.RunPython(watchlist_type_choice_text_to_int),

        # Remove text based choices
        migrations.RemoveField(
            model_name='anime',
            name='season',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='season_int',
            new_name='season',
        ),

        migrations.RemoveField(
            model_name='character',
            name='role'
        ),
        migrations.RenameField(
            model_name='character',
            old_name='role_int',
            new_name='role',
        ),

        migrations.RemoveField(
            model_name='image',
            name='type'
        ),
        migrations.RenameField(
            model_name='image',
            old_name='type_int',
            new_name='type',
        ),

        migrations.RemoveField(
            model_name='watchlist',
            name='type'
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='type_int',
            new_name='type',
        ),
    ]
