# Generated by Django 4.2.25 on 2025-10-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('watchlist', '0001_initial'),
        ('accounts', '0001_initial'),
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_by', through='watchlist.WatchList', to='anime.anime'),
        ),
    ]
