# Generated by Django 4.2.25 on 2025-10-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mal_id', models.PositiveIntegerField(unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('aired_from', models.DateField(blank=True, null=True)),
                ('aired_till', models.DateField(blank=True, null=True)),
                ('synopsis', models.TextField()),
                ('season', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Spring'), (1, 'Summer'), (2, 'Fall'), (3, 'Winter')], null=True)),
                ('rating', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('mal_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'Main'), (1, 'Supporting')], default=0)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='anime.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=20)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_actors', to='anime.character')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_japanese', models.CharField(blank=True, max_length=100, null=True)),
                ('aired', models.DateField(blank=True, null=True)),
                ('filler', models.BooleanField(default=False)),
                ('recap', models.BooleanField(default=False)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.anime')),
            ],
        ),
    ]
