# Generated by Django 4.2.25 on 2025-10-17 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engagement', '0001_initial'),
        ('anime', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_characters', through='engagement.CharacterLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='anime', to='anime.genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='anime', to='media.image'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(related_name='anime', to='anime.studio'),
        ),
    ]
