# Generated by Django 4.2.25 on 2025-10-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'jpg'), (1, 'webp')], default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('small_image_url', models.URLField(blank=True, null=True)),
                ('large_image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
